// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPPdKFCIRYrJxkCC7lEtyQ2BmXBBuxwRo',
    appId: '1:311528349463:web:44158eae631ca8edec6152',
    messagingSenderId: '311528349463',
    projectId: 'currencyconverter-95f7f',
    authDomain: 'currencyconverter-95f7f.firebaseapp.com',
    storageBucket: 'currencyconverter-95f7f.firebasestorage.app',
    measurementId: 'G-DK8H7F83JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy-H-X7VtvwtbVxsUs1Tp3_gT7R1u4ZAA',
    appId: '1:311528349463:android:34dc6e82240bbd70ec6152',
    messagingSenderId: '311528349463',
    projectId: 'currencyconverter-95f7f',
    storageBucket: 'currencyconverter-95f7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQRh2F63oYbQs8ik_NujOeHazE0qi5MoE',
    appId: '1:311528349463:ios:90a480cb64436e09ec6152',
    messagingSenderId: '311528349463',
    projectId: 'currencyconverter-95f7f',
    storageBucket: 'currencyconverter-95f7f.firebasestorage.app',
    iosBundleId: 'com.example.currencyConverter',
  );
}
